# 1) wpp to create a class Student with instance varuables rno, nm, 
# marks of 3 suject as list and dispaly marksheet on the screen.
# create at least 3 objects and get the data from user


# class Student:
# 	def __init__(self,rno,name,marks):
# 		self.rno = rno
# 		self.name = name
# 		self.marks = marks
# 	def display(self):
# 		print("Rno : %d \nName : %s "%(self.rno,self.name))
# 		self.m1,self.m2,self.m3 = [int(i) for i in marks]
# 		print("Subject1 : %d \nSubject2 : %d \nSubject3 : %d \n"%(self.m1,self.m2,self.m3))

# rno = int(input("Enter Id : "))
# name = input("Enter Name : ")
# marks = [int(i) for i in input("Enter Marks of 3 Subject : ").split()]
# s1 = Student(rno,name,marks)
# s1.display()

# rno = int(input("Enter Id : "))
# name = input("Enter Name : ")
# marks = [int(i) for i in input("Enter Marks of 3 Subject : ").split()]
# s2 = Student(rno,name,marks)
# s2.display()

# rno = int(input("Enter Id : "))
# name = input("Enter Name : ")
# marks = [int(i) for i in input("Enter Marks of 3 Subject : ").split()]
# s3 = Student(rno,name,marks)
# s3.display()


# 2) wpp to create class Bank with instance variables name, balance, acnt id should
# be autogenerated. 3 methods withdraw, deposit, showbalance. it is required min 
# balance should be 5000. create at least 3 bank objects and print the balance.
# min passbook

class Bank:
	bid = 0
	def __init__(self,name,balance):
		if(balance<5000):
			print("Balance should be more than 5000")
		else:
			Bank.bid += 1
			self.statement = []
			self.bid = Bank.bid
			self.balance = balance
			self.name = name
			self.statement.append("Account created for %s with Balance %d"%(self.name,self.balance))

	def withdraw(self,amt):
		if(self.balance-amt<5000):
			print("Transaction Declined\nMinimum Balance should be 5000")
		else:
			self.balance = self.balance - amt
			self.statement.append("Debited  %d"%amt)
	def deposit(self,amt):
		self.balance = self.balance + amt
		self.statement.append("Credited  %d"%amt)

	def showbalance(self):
		print("Your Balance :",self.balance)
	def display(self):
		print("*"*50)
		print("Account No : BBBB5555%d"%self.bid,"\nName :",self.name,"\nBalance :",self.balance)
		print("\n\nMini Statement")
		print("*"*50)
		for i in self.statement:
			print(i)
		print("*"*50)



name = input("Enter Name : ")
balance = int(input("Enter Balance : "))
b1 = Bank(name,balance)
b1.showbalance()
b1.withdraw(500)
b1.showbalance()
b1.deposit(2000)
b1.showbalance()
b1.display()

print("*"*50)
name = input("Enter Name : ")
balance = int(input("Enter Balance : "))
b2 = Bank(name,balance)
b2.showbalance()
b2.withdraw(100)
b2.showbalance()
b2.deposit(3000)
b2.showbalance()
b2.display()

